"use client";

/**
 * =========================================================
 * BACKUP - BaseCalculatorLayout with LaserBeam Animation
 * =========================================================
 * 
 * Created: January 8, 2026
 * 
 * This is a BACKUP - Do NOT edit this file!
 * If you break the original, copy this back to:
 * components/calculators/BaseCalculatorLayout.jsx
 * 
 * =========================================================
 */

import { DisclaimerFooter } from "@/components/calculators/DisclaimerFooter";
import { LaserBeam } from "@/components/LaserBeamCanvas";

export function BaseCalculatorLayout({
  header,
  children,
  disclaimer = null,
  maxWidthClass = "max-w-md lg:max-w-6xl",
  laserColor = "#c0a062", // Matte gold - matches calculator theme
  laserEnabled = true,
}) {
  const innerContent = (
    <div className={`calculator-container w-full ${maxWidthClass}`}>
      <div className="calculator-inner tabular-nums">
        {header}
        {children}
      </div>
      {disclaimer ? <DisclaimerFooter>{disclaimer}</DisclaimerFooter> : null}
    </div>
  );

  return (
    <div className="w-full flex justify-center calculator-backdrop-hover">
      {laserEnabled ? (
        <LaserBeam
          width="100%"
          height="auto"
          color={laserColor}
          borderRadius={12}
          duration={6}
          glowIntensity={18}
          beamLength={0.10}
          borderWidth={0}
          backgroundColor="transparent"
        >
          {innerContent}
        </LaserBeam>
      ) : (
        innerContent
      )}
    </div>
  );
}
