"use client";

import { useState, useCallback } from "react";
import jsPDF from "jspdf";

interface DownloadReportProps {
  monthlyAmount: number;
  durationYears: number;
  storyChoice: string;
  behavioralCost: number;
  disciplineAmt: number;
  choiceAmt: number;
  totalInvested: number;
}

export function DownloadReport({
  monthlyAmount,
  durationYears,
  storyChoice,
  behavioralCost,
  disciplineAmt,
  choiceAmt,
  totalInvested,
}: DownloadReportProps) {
  const [generating, setGenerating] = useState(false);

  const formatAmount = (amount: number): string => {
    if (amount >= 10_000_000) return `₹${(amount / 10_000_000).toFixed(2)} Cr`;
    if (amount >= 100_000) return `₹${(amount / 100_000).toFixed(2)} Lakh`;
    return `₹${Math.round(amount).toLocaleString("en-IN")}`;
  };

  const choiceLabel = (choice: string): string => {
    if (choice === "continue") return "Continue SIP (Disciplined)";
    if (choice === "pause_6") return "Pause for 6 months";
    if (choice === "pause_12") return "Pause for 12 months";
    return "Stop SIP (Panic)";
  };

  const generatePDF = useCallback(async () => {
    setGenerating(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      let y = 20;

      // Header
      doc.setFontSize(22);
      doc.setTextColor(40, 40, 40);
      doc.text("SIP vs Panic Selling Analysis", pageWidth / 2, y, { align: "center" });
      
      y += 12;
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("Education-Only Report | Generated by Premium Invest", pageWidth / 2, y, { align: "center" });
      
      y += 8;
      doc.text(`Generated: ${new Date().toLocaleDateString("en-IN", { dateStyle: "long" })}`, pageWidth / 2, y, { align: "center" });

      // Divider
      y += 10;
      doc.setDrawColor(200, 200, 200);
      doc.line(20, y, pageWidth - 20, y);

      // Input Summary
      y += 15;
      doc.setFontSize(14);
      doc.setTextColor(40, 40, 40);
      doc.text("Your Investment Parameters", 20, y);
      
      y += 10;
      doc.setFontSize(11);
      doc.setTextColor(60, 60, 60);
      doc.text(`Monthly SIP Amount: ₹${monthlyAmount.toLocaleString("en-IN")}`, 25, y);
      y += 7;
      doc.text(`Investment Duration: ${durationYears} years`, 25, y);
      y += 7;
      doc.text(`Total Invested: ${formatAmount(totalInvested)}`, 25, y);
      y += 7;
      doc.text(`Your Choice During Crash: ${choiceLabel(storyChoice)}`, 25, y);

      // Results Section
      y += 15;
      doc.setFontSize(14);
      doc.setTextColor(40, 40, 40);
      doc.text("Simulation Results", 20, y);

      // Results boxes
      y += 12;
      
      // Discipline Box
      doc.setFillColor(240, 248, 240);
      doc.roundedRect(20, y, pageWidth - 40, 25, 3, 3, "F");
      doc.setFontSize(10);
      doc.setTextColor(40, 120, 40);
      doc.text("If You Stay Disciplined:", 25, y + 8);
      doc.setFontSize(16);
      doc.text(formatAmount(disciplineAmt), 25, y + 18);

      // Choice Box
      y += 30;
      doc.setFillColor(255, 245, 238);
      doc.roundedRect(20, y, pageWidth - 40, 25, 3, 3, "F");
      doc.setFontSize(10);
      doc.setTextColor(180, 100, 40);
      doc.text(`Your Choice (${choiceLabel(storyChoice)}):`, 25, y + 8);
      doc.setFontSize(16);
      doc.text(formatAmount(choiceAmt), 25, y + 18);

      // Cost Box
      y += 30;
      doc.setFillColor(255, 235, 235);
      doc.roundedRect(20, y, pageWidth - 40, 30, 3, 3, "F");
      doc.setFontSize(10);
      doc.setTextColor(180, 40, 40);
      doc.text("Behavioral Cost (Potential Loss):", 25, y + 8);
      doc.setFontSize(20);
      doc.text(formatAmount(behavioralCost), 25, y + 22);

      // Cost Percentage
      const costPct = disciplineAmt > 0 ? Math.round((behavioralCost / disciplineAmt) * 100) : 0;
      doc.setFontSize(11);
      doc.text(`That's ${costPct}% less than disciplined investing`, pageWidth - 25, y + 22, { align: "right" });

      // Key Insights
      y += 40;
      doc.setFontSize(14);
      doc.setTextColor(40, 40, 40);
      doc.text("Key Behavioral Finance Insights", 20, y);

      y += 10;
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      const insights = [
        "• Panic selling during market crashes often locks in losses",
        "• SIP continues to buy units at lower prices during downturns",
        "• When markets recover, extra units bought cheap can compound significantly",
        "• Behavioral costs can exceed market volatility costs",
        "• Time in the market often beats timing the market",
      ];
      
      for (const insight of insights) {
        doc.text(insight, 25, y);
        y += 7;
      }

      // Disclaimer
      y += 10;
      doc.setFillColor(245, 245, 245);
      doc.roundedRect(20, y, pageWidth - 40, 35, 3, 3, "F");
      y += 8;
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text("IMPORTANT DISCLAIMER", 25, y);
      y += 6;
      doc.setFontSize(8);
      const disclaimer = "This is an education-only simulation using simplified models. Actual market behavior, returns, and tax implications may differ significantly. This is not investment advice. Past performance does not guarantee future results. Please consult a registered financial advisor before making investment decisions.";
      const splitDisclaimer = doc.splitTextToSize(disclaimer, pageWidth - 50);
      doc.text(splitDisclaimer, 25, y);

      // Footer
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text("www.premiuminvest.in | Education-Only Simulation", pageWidth / 2, 285, { align: "center" });

      // Save
      doc.save(`SIP-Analysis-${new Date().toISOString().split("T")[0]}.pdf`);
    } catch (error) {
      console.error("PDF generation failed:", error);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setGenerating(false);
    }
  }, [monthlyAmount, durationYears, storyChoice, behavioralCost, disciplineAmt, choiceAmt, totalInvested]);

  return (
    <button
      onClick={generatePDF}
      disabled={generating}
      className="flex items-center justify-center gap-2 w-full py-3 rounded-xl border border-[oklch(0.78_0.08_65/0.3)] bg-[oklch(0.10_0.02_264)] text-[oklch(0.85_0.06_65)] font-medium text-sm hover:bg-[oklch(0.15_0.02_264)] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
    >
      {generating ? (
        <>
          <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          Generating PDF...
        </>
      ) : (
        <>
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          📄 Download Your Analysis (PDF)
        </>
      )}
    </button>
  );
}
